### ISSUE TITLE
Showing the wrong group, can't search

### ISSUE THREAD

**Issue by figueroadavid** [freeCodeCamp/study-group-directory#10]
I am having the same problem as "Not showing correct closest study group. #9"  It is showing me Los Angeles. I'd guess it is probably because my ISP is AT&T.

However, the search field doesn't seem to work? so I can't pull anything..

David F.

**Comment by ginoskotheon** [comment]
@figueroadavid Hmm... I just tried the search and it worked for me. Where are you located?

**Comment by figueroadavid** [comment]
Houston, TX

I couldn't click on any of (what appeared to be) form fields..

David F.

**Comment by ginoskotheon** [comment]
@figueroadavid Weird. I just tried it from my computer and no problem. Any errors in the console? Which browser are you using?

**Comment by figueroadavid** [comment]
Chrome

David F.

**Comment by ginoskotheon** [comment]
@figueroadavid It totally worked for me. I even emulated Houston's lat and long. No problems. I'll keep running some tests. Are you getting any errors in the console?

**Comment by figueroadavid** [comment]
No.. I literally just have nothing to click on..

David F.

**Comment by ginoskotheon** [comment]
@figueroadavid Is it still an issue today? If you wouldn't mind, could you post a screen shot? Thanks.

**Comment by figueroadavid** [comment]
I finally got it.. Apparently I was on the wrong page..

Thank you,

David F.

On Fri, Apr 14, 2017 at 10:29 AM, William McDonald <notifications@github.com

**Comment by ginoskotheon** [comment]
@figueroadavid Great! Glad it's working!
