### ISSUE TITLE
Freecodecamp Belagavi

### ISSUE THREAD

**Issue by bsidio** [freeCodeCamp/study-group-directory#102]
https://www.facebook.com/groups/freecodecamp.bgm/

**Comment by johnkennedy9147** [comment]
@bsidio 
thanks I'll add this in the next update

**Comment by johnkennedy9147** [comment]
@bsidio Hi, is BGM a well known name for Belagavi. If not it would be better to rename the group so its easier for people to find.

**Comment by bsidio** [comment]
@johnkennedy9147  Yes its a well know name
