### ISSUE TITLE
Study Group for Chico, CA not appearing on list

### ISSUE THREAD

**Issue by MalcolmXX** [freeCodeCamp/study-group-directory#104]
Hey freeCodeCamp,

Chico isn't appearing on the list of facebook groups of freeCodeCampers. Can it be added please? Here is the link. 

https://www.facebook.com/groups/free.code.camp.chico/

Also here is a photo of our 1st meetup, that we did on the 11th of April, we are trying to meet every two weeks! 
![img_20180410_154327715_hdr](https://user-images.githubusercontent.com/7766040/39465228-07ed643e-4cd7-11e8-9201-b3b10eeebb5c.jpg)
![img_20180410_154336084_hdr](https://user-images.githubusercontent.com/7766040/39465231-0f00dfbc-4cd7-11e8-9c03-36f08b4c0457.jpg)

**Comment by johnkennedy9147** [comment]
@MalcolmXX Hi, I added an entry for Chico in #77 which was merged on 1st April.
Can you confirm you still dont see it?

**Comment by johnkennedy9147** [comment]
comment on PR #77 
![image](https://user-images.githubusercontent.com/26827682/39785354-c5c8904a-5313-11e8-89a8-16dbf0da0187.png)

**Comment by johnkennedy9147** [comment]
hi, @MalcolmXX I put a copy of yoru comment from PR here please keep all replies on this issue for easier follow up, thanks.
The group appears for me (see below) can you provide more information on the issue?
![image](https://user-images.githubusercontent.com/26827682/39785393-ec366b08-5313-11e8-85eb-052531d66e87.png)

**Comment by MalcolmXX** [comment]
Thanks John it is now appearing for me!

--
Giovanni Brown
Email: gbrown436@gmail.com

**Comment by johnkennedy9147** [comment]
OK thats great, thanks for letting me know, I'll close this issue.
