### ISSUE TITLE
FreeCodeCamp Bauchi

### ISSUE THREAD

**Issue by Muhdembo** [freeCodeCamp/study-group-directory#105]
FreeCodeCamp Bauchi group not appearing on the list

**Comment by johnkennedy9147** [comment]
@Muhdembo please provide the group url

**Comment by Muhdembo** [comment]
Below is the group URL

https://web.facebook.com/groups/free.code.camp.bauchi.nigeria

**Comment by johnkennedy9147** [comment]
@Muhdembo 
thanks I'll add this in the next update
