### ISSUE TITLE
New Free Code Camp City Group

### ISSUE THREAD

**Issue by diaaalhak** [freeCodeCamp/study-group-directory#113]
Hello,

Please add the city of Morocco / Tétouan to the cities of Free Code Camp 
[](https://www.facebook.com/groups/free.code.camp.tetouan/)

BR

**Comment by johnkennedy9147** [comment]
@diaaalhak please provide the url for the group

**Comment by diaaalhak** [comment]
Here is it  @johnkennedy9147 
https://www.facebook.com/groups/free.code.camp.tetouan/

**Comment by johnkennedy9147** [comment]
@diaaalhak 
thanks I'll add this in the next update

**Comment by diaaalhak** [comment]
Coooool , thank you very much @johnkennedy9147
