### ISSUE TITLE
CanTho, VN FreeCodeCamp facebook group

### ISSUE THREAD

**Issue by ancs21** [freeCodeCamp/study-group-directory#116]
Hello,
Please add my city Can Tho, Vietnam
fb url: https://www.facebook.com/groups/freecodecamp.canthocity/

Thanks!!

**Comment by johnkennedy9147** [comment]
@ancs21 
thanks I'll add this in the next update

**Comment by johnkennedy9147** [comment]
@anthonygallina1 hi, please leave the issues open until the groups have been added, thanks
