### ISSUE TITLE
Shows Vellore, Tamil Nadu, India as being close to Toronto, Ontario, Canada

### ISSUE THREAD

**Issue by oliver-daniel** [freeCodeCamp/study-group-directory#12]
## Description:
When using the directory from a location in Toronto, the five closest FCC groups are shown as follows:
- Toronto, Ontario, Canada - 7.57 km
- **Vellore, Tamil Nadu, India - 16.85 km**
- Markham, Ontario, Canada - 18.23 km
- Richmond Hill, Ontario, Canada - 18.62 km
- Mississauga, Ontario, Canada - 21.59 km

## How to reproduce:
Use the directory from a location in Toronto.

**Comment by ginoskotheon** [comment]
@oliver-daniel Working on it.
