### ISSUE TITLE
FreeCodeCamp Surat Gujarat

### ISSUE THREAD

**Issue by S-Jaydip** [freeCodeCamp/study-group-directory#123]
https://www.facebook.com/groups/free.code.camp.surat.gujarat/

**Comment by johnkennedy9147** [comment]
Hi, there is an entry in the directory already for Surat, Gujarat:
[https://www.facebook.com/groups/free.code.camp.surat](https://www.facebook.com/groups/free.code.camp.surat)
Full entry:
  {
    "url": "https://www.facebook.com/groups/free.code.camp.surat",
    "city": "Surat",
    "state": "Gujarat",
    "country": "India",
    "coordinates": "21.186461, 72.808128",
    "photoUrl": ""
  }

I checked and the group is still active.

**Comment by johnkennedy9147** [comment]
@S-Jaydip Closing issue - group will not be added as per earlier comment there is already a group in that location.  If you feel there is a reason to have two groups in the same location please reopen the issue and  provide further information.  thanks
