### ISSUE TITLE
Ensenada's freeCodeCamp Group

### ISSUE THREAD

**Issue by ekiim** [freeCodeCamp/study-group-directory#132]
I've created this group to involve members of my community, hope we get traction. 
https://www.facebook.com/groups/free.code.camp.ensenada.mexico/
https://www.facebook.com/groups/449213732170320/

**Comment by agrija9** [comment]
Hi Ensenada's freeCodeCamp,

It is nice to see people interested in forming this kind of group. What are you guys up to (more specifically)?

**Comment by ekiim** [comment]
My friends and some coworkers are interested in many of the subjects you offer, and we want to be able to label ourselves, and try to expand the community some coding groups are forming around in the city, and we want to build a big community. so basically just been part of a group where we can learn and share.

**Comment by agrija9** [comment]
So, if I understood correctly, you just want to create a coding community to share ideas and learn new topics. 

In the following months, I'll be working on some machine learning related projects, if something interesting shows up I'll let you know my advances guys (:

Keep it up!

**Comment by johnkennedy9147** [comment]
group added
