### ISSUE TITLE
freeCodeCamp Shiraz,Iran

### ISSUE THREAD

**Issue by techminto** [freeCodeCamp/study-group-directory#135]
Unfortunately Facebook is banned in the country and nobody could come to study group duo to that.

I did all the same in [here](https://gitter.im/freeCodeCampShiraz) as a replace
could the Mr. collaborator accept that?

Facebook is impossible for our study group

**Comment by johnkennedy9147** [comment]
@techminto looking into how we will handle this, will get back to you as soon as I know. thanks

**Comment by techminto** [comment]
what is the result?

**Comment by johnkennedy9147** [comment]
Hi, @techminto we are accepting other sites in addition to facebook groups.  I will add an entry to the directory for your group shortly.
