### ISSUE TITLE
freeCodeCamp Gaya

### ISSUE THREAD

**Issue by Mayankgbrc** [freeCodeCamp/study-group-directory#144]
https://www.facebook.com/groups/freecodecamp.gaya/

**Comment by johnkennedy9147** [comment]
@Mayankgbrc 
Please open a new issue using the New Study Group template
![image](https://user-images.githubusercontent.com/26827682/40485858-8ecb4f2e-5f57-11e8-9b2f-a09bab9ed62d.png)

**Comment by johnkennedy9147** [comment]
@Mayankgbrc Reopening this as the forum post was linking straight into a default new issue rather than the New Study group template so you wouldn't have known to use it.  I'll add this group shortly.
