### ISSUE TITLE
freeCodeCamp Fadeyi, Lagos

### ISSUE THREAD

**Issue by opelio** [freeCodeCamp/study-group-directory#147]
https://www.facebook.com/groups/freeCodeCamp.Fadeyi/

**Comment by johnkennedy9147** [comment]
@opelio Please raise a new issue and provide the information requested in the New study group template

**Comment by johnkennedy9147** [comment]
@opelio Reopening this as the forum post was linking straight into a default new issue rather than the New Study group template so you wouldn't have known to use it. I'll add this group shortly.
