### ISSUE TITLE
Migdal Haemek, Israel

### ISSUE THREAD

**Issue by arielwainberg** [freeCodeCamp/study-group-directory#148]
https://www.facebook.com/groups/free.code.camp.migdal.haemek/

**Comment by johnkennedy9147** [comment]
@arielwainberg 
Please open a new issue using the New Study Group template
![image](https://user-images.githubusercontent.com/26827682/40485858-8ecb4f2e-5f57-11e8-9b2f-a09bab9ed62d.png)
