### ISSUE TITLE
Migdal Hamek - Israel : New study group

### ISSUE THREAD

**Issue by arielwainberg** [freeCodeCamp/study-group-directory#149]
---
name: New study group
about: Raise a request to add a new study group

---

Please provide the following information to aid in adding your group to the directory:

### Esssential
- [ ] Group URL : https://www.facebook.com/groups/free.code.camp.migdal.haemek/
- [ ] Town or City group is located in : Migdal Haemek
- [ ] Country : Israel

### If you have one
- [ ] URL of Group Photo: "https://scontent.fhfa2-1.fna.fbcdn.net/v/t31.0-8/11958295_770704933056814_1479792634821157494_o.jpg?_nc_cat=0&oh=2476247619b8db56e335e0de4f8a6883&oe=5B92C4F3"

**Comment by johnkennedy9147** [comment]
@arielwainberg Thanks, it might be a week or two before I get this added. Please leave the issue open and I will close it once the group is added.

**Comment by arielwainberg** [comment]
Hey ,
Thanks for the respond.

I think I have mistaked with city name, its should be "Migdal Haemek",

Thanks in advance,
Ariel Wainberg.

בתאריך יום ה׳, 24 במאי 2018, 15:56, מאת John Kennedy ‏<
notifications@github.com>:
