### ISSUE TITLE
FreeCodeCamp Ourinhos, SP, Brasil

### ISSUE THREAD

**Issue by rezenderaul** [freeCodeCamp/study-group-directory#150]
[https://www.facebook.com/groups/803177203212919/](url)

**Comment by johnkennedy9147** [comment]
@rezenderaul 
Please open a new issue using the New Study Group template
![image](https://user-images.githubusercontent.com/26827682/40485858-8ecb4f2e-5f57-11e8-9b2f-a09bab9ed62d.png)
