### ISSUE TITLE
freecodecamp Palembang,Indonesia

### ISSUE THREAD

**Issue by vickzjr** [freeCodeCamp/study-group-directory#154]

**Comment by johnkennedy9147** [comment]
@vickzjr 
Please open a new issue using the New Study Group template
![image](https://user-images.githubusercontent.com/26827682/40485858-8ecb4f2e-5f57-11e8-9b2f-a09bab9ed62d.png)

**Comment by johnkennedy9147** [comment]
@vickzjr Reopening this as the forum post was linking straight into a default new issue rather than the New Study group template so you wouldn't have known to use it.  I'll add this group shortly.
