### ISSUE TITLE
Problem with fetching nearest study group

### ISSUE THREAD

**Issue by raisedadead** [freeCodeCamp/study-group-directory#16]
@PawanMKumar :

Hey Guys,
There was the problem fetching nearest study groups.
When I try to search nearest study groups based on my location, it was showing groups which is somewhere else.

I tried to search from Hyderabad location in India, It was showing Hyderabad from India along with Hyderabad in Pakistan too with same distance.

I'm using in Chrome in Android 6.0

Please find the screenshot 

http://share.pho.to/Afw7c

Refererence: https://github.com/freeCodeCamp/freeCodeCamp/issues/14513

**Comment by ginoskotheon** [comment]
@raisedadead I'll fix it.

**Comment by ginoskotheon** [comment]
@should be fixed, now.

**Comment by raisedadead** [comment]
@ginoskotheon thanks for the fix, you are awesome-er for managing this resource!. 
@PawanMKumar can you confirm? If yes, then we could close this.

**Comment by PawanMKumar** [comment]
@raisedadead
@ginoskotheon

Great work Guys.
It's working and I see a drop down too.

Awesome guys

**Comment by raisedadead** [comment]
@PawanMKumar Great! Thanks for confirming.
