### ISSUE TITLE
Geolocation and search don't work at all in mobile safari

### ISSUE THREAD

**Issue by QuincyLarson** [freeCodeCamp/study-group-directory#18]

**Comment by ginoskotheon** [comment]
@QuincyLarson is this just a problem when you're not connected to wifi?

**Comment by dexrualo** [comment]
Seems fine on my children's iPads.

**Comment by zalew16** [comment]
#18

**Comment by johnkennedy9147** [comment]
@QuincyLarson this still an issue?

**Comment by QuincyLarson** [comment]
@johnkennedy9147 I just tried this and it's no longer a problem. Thanks! Closing the issue.
