### ISSUE TITLE
FreeCodeCamp Derventa, Bosnia and Herzegovina request

### ISSUE THREAD

**Issue by stankovicsrdjo** [freeCodeCamp/study-group-directory#183]
Please provide the following information to aid in adding your group to the directory:

### Esssential
- [https://www.facebook.com/groups/freecodecamp.derventa/ ] Group URL (Web address)
- [ Derventa ] Town or City group is located in
- [ Republika Srpska ] State / County / Region
- [ Bosnia and Herzegovina ] Country

### Nice to have
- [ 44.97839 17.90779 ] Co-ordinates

### If you have one
- [ ] URL of Group Photo

**Comment by ddddamian** [comment]
PR submitted
