### ISSUE TITLE
FreeCodeCamp Buchholz in der Nordheide

### ISSUE THREAD

**Issue by mspkom** [freeCodeCamp/study-group-directory#189]
Please provide the following information to aid in adding your group to the directory:

### Esssential
- [https://www.facebook.com/groups/455966358240435/] Group URL (Web address)
- [Buchholz in der Nordheide] Town or City group is located in
- [Niedersachsen] State / County / Region
- [Germany] Country

### Nice to have
- [9.866667, 53.316667] Co-ordinates

### If you have one
- [ ] URL of Group Photo

**Comment by ddddamian** [comment]
PR submitted
