### ISSUE TITLE
freeCodeCamp Group: Hassloch (Germany/Deutschland)

### ISSUE THREAD

**Issue by ilindaniel** [freeCodeCamp/study-group-directory#191]
Please provide the following information to aid in adding your group to the directory:

### Esssential
- [https://www.facebook.com/groups/free.code.camp.hassloch/ ] Group URL (Web address)
- [ Hassloch ] Town or City group is located in
- [Rheinland-Pfalz ] State / County / Region
- [ Deutschland ] Country

### Nice to have
- [ ] Co-ordinates

### If you have one
- [ ] URL of Group Photo

**Comment by ddddamian** [comment]
PR submitted
