### ISSUE TITLE
freeCodeCamp Matsue Japan

### ISSUE THREAD

**Issue by regonn** [freeCodeCamp/study-group-directory#193]
### Esssential :gem: 
- [x] Group URL (Web address)
 - https://www.facebook.com/groups/free.code.camp.matsue/
- [x] Town or City group is located in
  - Matsue
- [x] State / County / Region
  - Shimane
- [x] Country
  - Japan

### Nice to have
- [x] Co-ordinates
  - Latitude: 35.46806
  - Longitude: 133.04861

**Comment by ddddamian** [comment]
PR submitted
