### ISSUE TITLE
https://www.facebook.com/groups/free.code.camp.amaravati.ap/  Amaravati, Andhra Pradesh, India.   16.5730° N, 80.3575° E .   

### ISSUE THREAD

**Issue by S-FK** [freeCodeCamp/study-group-directory#195]
Please provide the following information to aid in adding your group to the directory:

### Esssential
- [ ] Group URL (Web address)
- [ ] Town or City group is located in
- [ ] State / County / Region
- [ ] Country

### Nice to have
- [ ] Co-ordinates

### If you have one
- [ ] URL of Group Photo

**Comment by ddddamian** [comment]
PR submitted.

**Comment by johnkennedy9147** [comment]
per this comment closing - https://github.com/freeCodeCamp/study-group-directory/pull/196#issuecomment-424993653
