### ISSUE TITLE
Use CircleCI for JSON linting

### ISSUE THREAD

**Issue by QuincyLarson** [freeCodeCamp/study-group-directory#20]
Since we're going to be accepting lots of pull requests for new study groups, and updated images for existing study groups, we want to ensure that our JSON doesn't break (since JSON is quite easy to break by omitting a comma or double quote). 

I recommend we install CircleCI, which can validate the JSON file. This way, we'll know that the JSON is valid before accepting PRs without having to manually check each time.

**Comment by ginoskotheon** [comment]
@QuincyLarson Excellent work, Quincy.
