### ISSUE TITLE
Can't Load Cities

### ISSUE THREAD

**Issue by TheOtherZ** [freeCodeCamp/study-group-directory#21]
I just dropped by to look for some study groups and noticed that no city information was being displayed.

Looks like the campsites2.json file was replaced, but main.js is still trying to reference campsites2.json.

**Comment by ginoskotheon** [comment]
Yeah that was my bad!

**Comment by TheOtherZ** [comment]
No problem! I am now browsing my local study groups with ease. Good work on the site!
