### ISSUE TITLE
Add San Miguel de Tucumán, Argentina to the Study Group Directory

### ISSUE THREAD

**Issue by DaniNz** [freeCodeCamp/study-group-directory#224]
Please provide the following information to aid in adding your group to the directory:

### Esssential
- [ https://web.facebook.com/groups/free.code.camp.smtucuman] Group URL (Web address)
- [San Miguel de Tucumán  ] Town or City group is located in
- [Tucumán / Noroeste ] State / County / Region
- [ Argentina] Country

### Nice to have
- [ -26.8241405, -65.2226028] Co-ordinates

### If you have one
- [ ] URL of Group Photo

**Comment by rodoviario** [comment]
Hi, I have made a PR with the changes suggested above. Also I am part of the Tucumán group. Im adding this comment as suggested in the contribution guidelines, to let you know. Please  tell me if there is something else to do in order to espect the PR to be commited. Thanks in advance.
