### ISSUE TITLE
Old Norwich groupd seems to be dead

### ISSUE THREAD

**Issue by alexiorodrigues** [freeCodeCamp/study-group-directory#242]
#### What was the expected behaviour
New freecodecampers being able to join, comment and organize meetings in the group that they want to join.

I've created a new group to replace the old one or at least create one that allows new members to join and participate. 

#### Old group
https://www.facebook.com/groups/free.code.camp.norwich.england/

#### New group (issue)
https://github.com/freeCodeCamp/study-group-directory/issues/238

#### Additional Information
What should be the correct behaviour to solve this kind of issues? besides having more than one admin in a group

**Comment by johnkennedy9147** [comment]
Hi. 

Unfortunately, groups sometimes do fizzle out, or never really get going.

There isn't much that can be done especially if the admin isn't responsive to messages or membership requests.

I'll add your new group to the directory and new campers will get equal visibility of both groups.

Hopefully there will be an opportunity to merge the groups in the future.

Best of luck with the new group.
