### ISSUE TITLE
FreeCodeCamp Essex United Kingdom 

### ISSUE THREAD

**Issue by ginnonlinecreative** [freeCodeCamp/study-group-directory#250]
Please provide the following information to aid in adding your group to the directory:

### Esssential
- [x] Group URL (Web address)
- [ ] Town or City group is located in
- [ ] State / County / Region
- [ ] Country

### Nice to have
- [ ] Co-ordinates

### If you have one
- [ ] URL of Group Photo

**Comment by johnkennedy9147** [comment]
None of the required information has been provided. Closing issue.
