### ISSUE TITLE
Add group Playas de Rosarito to study group directory

### ISSUE THREAD

**Issue by skulltrumbo** [freeCodeCamp/study-group-directory#253]
Please provide the following information to aid in adding your group to the directory:

### Esssential
- https://www.facebook.com/groups/594064667756287/
- Playas de Rosarito
- Baja California
- Mexico

**Comment by skulltrumbo** [comment]
URL updated. 
Was ~~https://www.facebook.com/groups/594064667756287/~~
Now it's: https://www.facebook.com/groups/freecodecamp.rosarito/

**Comment by ddddamian** [comment]
@skulltrumbo Do you have co-ordinates for this study group?
