### ISSUE TITLE
freeCodeCamp New Study Group

### ISSUE THREAD

**Issue by wayneasilva** [freeCodeCamp/study-group-directory#254]
Please provide the following information to aid in adding your group to the directory:

### Esssential
- [ https://www.facebook.com/groups/free.code.camp.new.bedford/] Group URL (Web address)
- [ New Bedford] Town or City group is located in
- [ Massachusetts] State / County / Region
- [ US] Country

### Nice to have
- [ ] Co-ordinates

### If you have one
- [ ] URL of Group Photo

**Comment by ddddamian** [comment]
@wayneasilva Do you have co-ordinates for this study group?
