### ISSUE TITLE
Add group - Detroit, MI, USA

### ISSUE THREAD

**Issue by rayray3899** [freeCodeCamp/study-group-directory#257]
Please provide the following information to aid in adding your group to the directory:

### Esssential
- [https://www.meetup.com/Detroit-Free-Code-Camp-Meetup/] Group URL (Web address)
- [Detroit] Town or City group is located in
- [Michigan] State / County / Region
- [United States] Country

### Nice to have
- [ ] Co-ordinates

### If you have one
- [ ] URL of Group Photo

**Comment by ddddamian** [comment]
@rayray3899 Do you have co-ordinates for this study group?
