### ISSUE TITLE
Hove, England is not close to Leuven, Belgium

### ISSUE THREAD

**Issue by cambscoder** [freeCodeCamp/study-group-directory#30]
There’s a bug in the web app. When I search for groups around Leuven (in Belgium) I get shown Hove, England being 30km from here. That’s off by a factor of 10 at least. Maybe Hove is just in the wrong place, or it's something more serious.

**Comment by ginoskotheon** [comment]
@cambscoder Probably just the wrong coordinates. I'll fix it.

**Comment by ginoskotheon** [comment]
@cambscoder Should be fixed now. Thanks!
