### ISSUE TITLE
Study Group Directory city location issue

### ISSUE THREAD

**Issue by kris-bosland** [freeCodeCamp/study-group-directory#38]
I am in the Portland, Oregon area.  When I let the study group directory use my location, it listed Portland, Maine as well as Portland, Oregon, and Salem, India as well as Salem, Oregon.  Chrome web browser and Windows 10, if it matters.  Thanks!

**Comment by johnkennedy9147** [comment]
Both Portlands have same co-ords in json entries, and Salem, India has co-ords for Salem Oregon.
I'll submit PR to fix

**Comment by johnkennedy9147** [comment]
This issue can be closed.

**Comment by raisedadead** [comment]
Thanks @johnkennedy9147

**Comment by cameldjoulako** [comment]
Hello my name is DJOULAKO Camel Léonce. I followed all the steps to create the Nkongsamba freecodecamp study group. but when you look for it in the cities, it does not appear. please, help me add it.
city: Nkongsamba
country: Cameroon
facebook group: www.facebook.com/free.code.camp.nkongsamba
my email address: cameldjoulako17@gmail.com

**Comment by raisedadead** [comment]
At @cameldjoulako we request you to stop commenting on the issues, we have a a work in progress change and the group will be added soon.

**Comment by cameldjoulako** [comment]
no is not same
Hello my name is DJOULAKO Camel Léonce. I followed all the steps to create the Nkongsamba freecodecamp study group. but when you look for it in the cities, it does not appear. sorry, help me add it.
city: Nkongsamba
country: Cameroon
facebook group: https://web.facebook.com/groups/free.code.camp.nkongsamba/
my email address: cameldjoulako17@gmail.com

**Comment by cameldjoulako** [comment]
thank you @raisedadead I understood
