### ISSUE TITLE
Beta: Distance calculations incorrect for finding a study group

### ISSUE THREAD

**Issue by raisedadead** [freeCodeCamp/study-group-directory#61]
@ReveurGAM commented on [Wed Jan 24 2018](https://github.com/freeCodeCamp/freeCodeCamp/issues/16562)

****Area & Link
[Join a study group](https://study-group-directory.freecodecamp.org/)

****Problem Description
(Sorry, I aborted a report before because there was no cancel button, but then this app wouldn't reload the template, so I'm writing without the template).

The website is not calculating distances correctly.  I highly doubt that CA is closer to Milwaukee, WI than WV, nor is it just past Sheboygan. ;)

****Browser & Environment
Chrome Version 63.0.3239.132 (Official Build) (64-bit)
Desktop with W7 Ultimate

****Screenshots
![image](https://user-images.githubusercontent.com/35181004/35300443-030e33ec-004e-11e8-8136-05df32687795.png)

**Comment by johnkennedy9147** [comment]
@raisedadead the issue here isn't miscalculation of distance, its wrong co-ordinates on the entry for Lake Forest, CA.  It has co-ords for Lake Forest, Illinois. I'll fix this.

**Comment by ReveurGAM** [comment]
@johnkennedy9147 
All of the distances are off somewhat, but within a reasonable number of miles (usually about 5).  However, Wheeling, WV, is also seriously wrong as it should show about 578 mi.

Thanks for your help!

**Comment by johnkennedy9147** [comment]
@ReveurGAM thanks for pointing that out, I've put in another PR to fix, again the co-ords were for a same name location in Il.  Regarding the others being a few miles out, it might just be you browser reporting your location as that of your internet provider, rather than where you are physically located at the time.

**Comment by ReveurGAM** [comment]
@johnkennedy9147 I'm not worried about those minor ones; I figured they are because the exact location may be outside of the stated city/town.   Your supposition also makes sense. :)

**Comment by johnkennedy9147** [comment]
@raisedadead Hi, this can be closed, fixed by two of my PRs yesterday, thanks.
