### ISSUE TITLE
Many groups missing from directory

### ISSUE THREAD

**Issue by johnkennedy9147** [freeCodeCamp/study-group-directory#68]
As previously discussed there are a large number of local study groups not listed in the directory.

This issue is to track the ongoing effort to identify and add the missing groups. 

At this point I have identified 83 groups to be added. 

This is from comparing the existing entries on the directory with the entries on the forum list, plus a few extras from group leaders...

These are now geo-coded and will be added in batches.

**Comment by johnkennedy9147** [comment]
All the missing groups that were listed in the forum have now been added.  

I am now going to ask in the freeCodeCamp group leaders group and on Gitter if they know of any other groups that may be still be missing. 

I've also been playing around with Facebook Graph API to see if it will let us extract a list of groups based on having freeCodeCamp in the url or name. Recent events might impact the ability to do this. 

@QuincyLarson Do you think it would be a good idea to go out via twitter and maybe a medium article and ask people to let us know of any groups still missing from the directory?

**Comment by QuincyLarson** [comment]
@johnkennedy9147 You're the man! Thank you so much for adding these groups to the directory!

> I've also been playing around with Facebook Graph API to see if it will let us extract a list of groups based on having freeCodeCamp in the url or name. Recent events might impact the ability to do this.

This is the best way to go about this. Please see if you can build a list of all Facebook groups with freeCodeCamp in the title. Then we can cross-reference this with our list on the directory. 

This is a much more efficient way to do this than trying to ask people elsewhere, and I think it's the logical next step. 

Again, thank you for everything you're doing with this.

**Comment by johnkennedy9147** [comment]
@QuincyLarson Using FaceBook Graph API no longer seems possible - recent (4th April) breaking changes have greatly reduced what you can search for including groups:
![image](https://user-images.githubusercontent.com/26827682/39097161-b65fa9ce-4650-11e8-968e-66186db5a388.png)

**Comment by QuincyLarson** [comment]
@johnkennedy9147 That's unfortunate, though not surprising considering all the trouble Facebook is now in. 

We are making steady progress on https://github.com/freeCodeCamp/open-api, after which we'll be able to build freeCodeCamp Events. Some of the groups created between now and then may slip through the proverbial cracks, but we're working as fast as we can.

**Comment by QuincyLarson** [comment]
@johnkennedy9147 I propose we go ahead and close this issue for now. You have added dozens of groups to the directory, and this has been a tremendous help. We would welcome your help designing the functionality of Events.

**Comment by johnkennedy9147** [comment]
I have an idea for a workaround but cant test it till Facebook reopens App review. I am also hopeful that they will add back some of the search features once they redesign it. I'll keep an eye on their updates and come back to this if it looks feasible in the future.

**Comment by raisedadead** [comment]
Would access to a current app work? I mean we do have access to the login with Facebook and its comes with certain permissions. Or add additional permissions to that app?

Let me know, I have dev access to the dashboard and can help. Also you can email me should you prefer that, `mrugesh at freecodecamp.org`

**Comment by johnkennedy9147** [comment]
@raisedadead Hi, it would need `user_managed_groups` permission. If it doesnt already have that it would need to go through App Review to get it working and presently they arent doing App reviews. I'm not sure if the available nodes and edges would actually return useful information for our purposes.
