### ISSUE TITLE
Two Lakewoods, one  camp

### ISSUE THREAD

**Issue by raisedadead** [freeCodeCamp/study-group-directory#84]
@spedoinkle commented on [Thu Apr 05 2018](https://github.com/freeCodeCamp/freeCodeCamp/issues/17028)

#### Find a local

https://study-group-directory.freecodecamp.org

#### Lakewood, Washington != Lakewood, Colorado

Lakewood, Washington has been entangled into the location of Lakewood, Colorado and Lakewood, Colorado has ceased to exist.

#### Browser Information

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code

```js



```

**Comment by spedoinkle** [comment]
Aha! So you say the Facebook group for Lakewood, Co does not exist! We must make it! Because Washington got us mixed up with Lakewood, Co. which I’m sure has a great amount of programmers that would love to join us!

**Comment by johnkennedy9147** [comment]
@spedoinkle If you search by state you will get a list of all the groups we know about in the state, If you want to create a new group check out this page [how-to-create-a-local-study-group](https://forum.freecodecamp.org/t/how-to-create-a-local-study-group/19532). You can then submit a PR on this repository to add it to the directory, just put an entry in  `study-group-directory/assets/json/campsitesfinal.json` and one of the maintainers will review it. If you need any help just give me a shout.  
@raisedadead I think this issue can be closed now.
