### ISSUE TITLE
Validate co-ordinates for groups

### ISSUE THREAD

**Issue by johnkennedy9147** [freeCodeCamp/study-group-directory#92]
As we have seen a lot of the entries have incorrect co-ordinates listed. 

Usually, they have the co-ordinates for another settlement with the same name. Eg two cities in US with same name but in different states, sometimes same names but in different countries.

We've fixed a bunch as they were brought to our attention but I want to proactively validate all the entries.

**Comment by adammustafa176** [comment]
good well done
