### ISSUE TITLE
https://www.facebook.com/groups/free.code.camp.fullerton.city/

### ISSUE THREAD

**Issue by odhiambo123** [freeCodeCamp/study-group-directory#95]
https://www.facebook.com/groups/free.code.camp.fullerton.city/

**Comment by johnkennedy9147** [comment]
@odhiambo123 Hi can you confirm this is Fullerton City, California?

**Comment by odhiambo123** [comment]
Sorry for the late response here @johnkennedy9147 yes I am based in Fullerton City, I just haven't had enough Fullerton people in the group yet. https://www.facebook.com/groups/free.code.camp.fullerton.city/ is based in Fullerton
